### ISSUE TITLE
Exporting Fails

### ISSUE THREAD

**Issue by neddonovan13** [oTranscribe/oTranscribe#101]
I am trying to export my transcript to plain text and getting the following screen

<img width="854" alt="screen shot 2019-01-31 at 4 22 31 pm" src="https://user-images.githubusercontent.com/42779390/52086260-6ad09780-2574-11e9-8ef6-b1d17dbaeeb9.png">

The Sign in to Google Drive is also not working, and the same screen appears with any attempt to export the transcription.

**Comment by freedmand** [comment]
Hey there,

I just pushed an update to the site that fixes exporting files in Safari. This should resolve your primary bug. If the Sign in to Google Drive is still not working, please create another issue to track it.

Thanks!
Dylan
