### ISSUE TITLE
Privacy policy says "we do not not store"

### ISSUE THREAD

**Issue by morisy** [oTranscribe/oTranscribe#113]
Should remove the extra "not" to remove confusion.

**Comment by mic-ray** [comment]
@morisy Should i fix this in the `src/privacy.htm` file?
I found that the second "not" is surronded in HTML `<b>` tags, however when inspecting the live site, the second "not" isn't rendered as bold (atleast in my browser).
I could fix this by wrapping the word in `<strong>` tags instead?
