### ISSUE TITLE
Windows install locally

### ISSUE THREAD

**Issue by JoWe89** [oTranscribe/oTranscribe#146]
Hi guys
I dont get it how to install it on Windows locally.
I installed node.js and run from a admin-CMD the command "npm install". That is doing his job, all good.
But now, how to compile the dist folder? The command "make build_prod" is not recognized in CMD. And which dist folder does it mean?
Bes regards

**Comment by amandabee** [comment]
Unfortunately, we're not able to troubleshoot individual installation issues. We recommend connecting with a community like StackOverflow that might be equipped to help.
