### ISSUE TITLE
Strange behaviour after exporting

### ISSUE THREAD

**Issue by ejb** [oTranscribe/oTranscribe#28]
Feedback from a user via email:

> After exporting my document to .txt file and I continue to transcribe my text, first of all my cursor seems to be gone but more importantly when I try to write a - ' - in for example "you'd" Firefox opens the search bar. That means I can't enter this key anymore. My fix is to reload the page and the audio file which is fine for me but I still wanted to let you know!

**Comment by DanielTosello** [comment]
This looks a lot like a known firefox issue with quicksearch...

**Comment by ejb** [comment]
Ah I see. Strange how it only occurs for the user after exporting though. I'm going to close this ticket since it's a minor issue without an obvious solution.
