### ISSUE TITLE
Keep text in middle of screen

### ISSUE THREAD

**Issue by ejb** [oTranscribe/oTranscribe#31]
A user sent a feature suggestion by email:

>  I had one suggestion for improvement I wanted to share. When you type enough for it to be at the bottom of the page, the tool keeps scrolling, but keeps your text at the bottom of the page. It would be easier to continue typing if the tool kept your typing towards the middle after you fill up the page. This makes me feel like I need to keep scrolling, which doesn’t quite work since it only adds like three blank lines at the end of the document after you fill up the first screen.

**Comment by sojusnik** [comment]
Signed!
