### ISSUE TITLE
Timestamps should include hours

### ISSUE THREAD

**Issue by ejb** [oTranscribe/oTranscribe#32]
A user writes:

> With the time stamps after 60 minutes oTranscribe continues on to 61, 62, etc etc so a 90 minute tape ends at 90 minutes. In almost all DAW's (protools, logic, reaper etc...) the time signatures after 60 minutes change format to hour so a 90 minute tape would be 1:30:00 instead of 90:00

**Comment by npentrel** [comment]
Addressed in [https://github.com/oTranscribe/oTranscribe/pull/63](https://github.com/oTranscribe/oTranscribe/pull/63).
