### ISSUE TITLE
Customizable shortcuts

### ISSUE THREAD

**Issue by barichello** [oTranscribe/oTranscribe#39]
I just started to use oTranscribe to transcribe group discussions for my PhD and the software really seems to be a wonderful option for the job.

What I would like to ask for is quite based on my use of it.
As I usually transcribe audios with more than one people talking, it would be useful if it was possible to configure shortcuts (for example, control+1, control+2, control+3...) to insert chunks of text. I would use it to insert the name of the person that is talking on each line.

For instance, before strat the transcription, I would configure control+1 to be "Interviewer: ", control+2 to be "Interviewee 1: " and control+3 to be "Interviewee 1: ". Then, I could use the every time the speaker changes.
It could also be used to save common events or particular flags to be inserted in the transcription.

**Comment by ejb** [comment]
Hi, I don't plan on adding this feature. I recommend using another app such as [Auto Text Expander](https://chrome.google.com/webstore/detail/auto-text-expander-for-go/iibninhmiggehlcdolcilmhacighjamp?hl=en) in conjunction with oTranscribe instead.

**Comment by barichello** [comment]
Fair enough.
Thanks for the suggestion anyway.
