### ISSUE TITLE
Google Drive export doesn't seem to work

### ISSUE THREAD

**Issue by cboulanger** [oTranscribe/oTranscribe#44]
I have authenticated sucessfully with Google Drive. Clicking on "Send Transcript to Google Drive" opens an empty tab, nothing is transferred. 

Windows 7/Firefox 39

**Comment by ejb** [comment]
Hi @cboulanger, I realise I'm _super_ late to this, but is it still broken for you?

**Comment by fpereira1** [comment]
Works great for me when I tried today.

**Comment by Garoe** [comment]
Hi, I´m getting the same problem using Ubuntu 16.04 / Firefox 49, but I don't have any problems with Chrome

**Comment by jmason888-berkeley** [comment]
I use Google multiple login. It works if I connect to my "primary" login (that shows up in Google Drive as https://drive.google.com/drive/u/0/, but not in the secondary https://drive.google.com/drive/u/1/).  This is not a big deal for me, but perhaps this sheds some light on the issue.

ChromeOS Version 59.0.3071.134 (Official Build) (64-bit)

**Comment by freedmand** [comment]
The Google drive export now works. The issue was Google cracked down on the authorization scope needed to export to Google drive, so we had to go through a separate approval process. It should now function for all users.
