### ISSUE TITLE
Remove black window when only audio is present

### ISSUE THREAD

**Issue by sojusnik** [oTranscribe/oTranscribe#48]
Removing the black window (see [this](http://i.imgur.com/vPxkGrf.png) picture) to the left of the text field would greatly improve the aesthetic perception of this great program, when only an audio file is played.

**Comment by ejb** [comment]
That window should only appear when playing a video file. What file type are you using?

**Comment by sojusnik** [comment]
An .ogg file.

Elliot Bentley <notifications@github.com> schrieb am Mi., 6. Jän. 2016
15:04:

> That window should only appear when playing a video file. What file type
> are you using?
>

**Comment by sojusnik** [comment]
This bug is still present.

**Comment by ejb** [comment]
I just tried a .ogg audio file in Chrome, and it worked fine. What browser are you using?

**Comment by sojusnik** [comment]
Latest Firefox :)

Elliot Bentley <notifications@github.com> schrieb am Mo., 12. Sep. 2016
00:13:

**Comment by ejb** [comment]
Unfortunately, I think this is a browser bug. Firefox is reporting the filetype as video, even though it's an audio file.

<img width="357" alt="screen shot 2016-09-11 at 18 38 02" src="https://cloud.githubusercontent.com/assets/1442752/18421078/f58587ee-784e-11e6-912f-fb989d635512.png">

**Comment by sojusnik** [comment]
Is there anything we can do to solve this issue with Firefox? Maybe fill some bug report or the like?

**Comment by ejb** [comment]
It seems there's already a ticket open for this issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1240259

I've added a note that it affects ogg files regardless of drag & drop.

**Comment by sojusnik** [comment]
Great, thanks!

**Comment by ejb** [comment]
Nothing I can do while Mozilla spin their wheels. Closing this issue.
