### ISSUE TITLE
Autosaving stopped working after a restart

### ISSUE THREAD

**Issue by sojusnik** [oTranscribe/oTranscribe#49]
The current version of Firefox (v43) has problems with saving the input after a restart. It seems, that Firefox changed the cookie management in the recent versions, because some months ago everything worked fine with untouched settings.

After experimenting with the cookie [settings](https://support.mozilla.org/en-US/kb/enable-and-disable-cookies-website-preferences), the only constellation that works is to keep the cookies "until they expire", although oTranscribe is in my whitelist, with both http and https. I'm certain, that in earlier versions of Firefox (about half a year ago) it also worked with "I close Firefox".

Does somebody experience the same?

**Comment by amandabee** [comment]
I'm closing out older issues that we don't have the capacity to troubleshoot, including this one.
