### ISSUE TITLE
Can't paste after export

### ISSUE THREAD

**Issue by sojusnik** [oTranscribe/oTranscribe#51]
After using the export function, it's not possible to paste text from the clipboard anymore. Although the text cursor is blinking, pasting via mouse or ctrl+v, isn't working. Only after a reload of the page (ctrl+r) pasting is possible again.

Observed with Firefox 43.04 64-bit under Ubuntu Gnome 15.10.

**Comment by amandabee** [comment]
I'm closing out older issues that we don't have the capacity to troubleshoot, including this one.
