### ISSUE TITLE
Custom timestamp offset

### ISSUE THREAD

**Issue by dperelman** [oTranscribe/oTranscribe#52]
Use case scenario: a transcription is desired for one long file which is split up into multiple segments for multiple transcribers to work on. Then the timestamps of the segments do not correspond to the timestamps of the entire file. Could there possibly be an advanced feature to manually enter the actual timestamp for `00:00` of the segment being transcribed so the recorded timestamps would be accurate for the entire file?

**Comment by amandabee** [comment]
I'm closing out older issues that we don't have the capacity to troubleshoot, including this one.
