### ISSUE TITLE
Additional keyboard shortcuts 

### ISSUE THREAD

**Issue by ejb** [oTranscribe/oTranscribe#58]
Suggested by Kurnia Adhiwibowo over email:

> Is there control to start from begining track? 0:00s. This feature also needed when i want to playback the track once more (replay) etc.
> 
> Go to spesific time. The timestap is very usefull one. But maybe we also need to go to spesific time. Like when we want to cross check our transkrip from spesific time. This just like Ctrl+G in Ms Word, when we want to jump to spesific pages.

**Comment by npentrel** [comment]
Addressing first part in [https://github.com/oTranscribe/oTranscribe/pull/62](https://github.com/oTranscribe/oTranscribe/pull/62) .

**Comment by ejb** [comment]
These are now both implemented.
