### ISSUE TITLE
Support opening YouTube videos via URL with supplied YouTube_ID parameter

### ISSUE THREAD

**Issue by MikeRidgway** [oTranscribe/oTranscribe#64]
I have a [Chrome extension](https://chrome.google.com/webstore/detail/diy-captions-launcher-for/nfmohppoonnamhhboojkgffnjmbekckl) which opens YouTube videos in transcription apps, specifically [DIY Captions](www.diycaptions.com) and [Amara.](www.amara.org) I would like to add oTranscribe to the list of options.

**Comment by ejb** [comment]
Cool extension! I'll put this on my to-do list, but I have some more pressing bugs to deal with first. Will post here if/when I have any updates.

**Comment by ejb** [comment]
Resolved by #68
