### ISSUE TITLE
Makefile doesn't work

### ISSUE THREAD

**Issue by 5-0-9** [oTranscribe/oTranscribe#65]
in Makefile  

_**compile_static:**_  section

cat "$${f}" More than one $

**Comment by ejb** [comment]
Thanks for reporting. What OS are you using? I use OS X 10.12.

**Comment by kekecha** [comment]
CentOS 6, $$ it should be current PID in bash

**Comment by ejb** [comment]
I had to look up what 'PID' meant, so I reckon you know more about this than I do :)

This line is intended to concatenate every file matched by the glob `src/l10n/*.ini` with a newline between each file. If you can come up with a better method that doesn't involve the `$$` (and I know there are dozens), I'd be happy to replace it.

    for f in src/l10n/*.ini; do (cat "$${f}"; echo) >> dist/data.ini; done
