### ISSUE TITLE
Problems skipping forward in time

### ISSUE THREAD

**Issue by ejb** [oTranscribe/oTranscribe#75]
Related (I think) bug reports from several users:

> When I want to fast forward for a long period of time, say 10:00, the time counter mysteriously shifts back to zero. This happens by pressing F2 but not when pressing Cntrl + 2.

> Every time I press "skip forwards", "skip backwards" or "pause" three times in a row the audio rewinds to start.

**Comment by jclwilson** [comment]
+1

Same issue for me, using Chrome 63 on Ubuntu 17.10, XFCE 4.12

**Comment by amandabee** [comment]
I believe this is working now.
