### ISSUE TITLE
Formatting is not preserved after importing a transcript exported from Classic version

### ISSUE THREAD

**Issue by anantakrishna** [oTranscribe/oTranscribe#82]
1. Exporting a transcript from http://otranscribe.com/classic/. It contains formatting (italics).
2. Importing the file into http://otranscribe.com/.
3. No formatting is preserved.

Whereas the following scenario works:
1. Formatting the text in http://otranscribe.com/classic/.
2. Opening http://otranscribe.com/.
3. The text is loaded from local storage with formatting.

**Comment by amandabee** [comment]
I'm closing out older issues that we don't have the capacity to troubleshoot, including this one.
