### ISSUE TITLE
Google speech API timestamps and text highlighting

### ISSUE THREAD

**Issue by koenvb** [oTranscribe/oTranscribe#83]
Hi, 
In my perfect world I would see the transcribing as following:

* Upload my audio
* Do a quick transcribe using the google speech api so I have a base to work from
* Load the text in the editor. 
* Because its using timestamps with the latest release I can just play the audio and the text is highlighted 
** Example like this: http://westonruter.github.io/html5-audio-read-along/

Not sure if it fits with this project but was wondering what your thoughts are on these
type of features.

**Comment by ejb** [comment]
I think this is beyond the scope of oTranscribe, sorry. There are a bunch of projects in development that _do_ do this, though. Like https://mercury.glitch.digital and https://trint.com – maybe one of those would suit your needs?

**Comment by koenvb** [comment]
Thanks, Another one I found in my search was this one:
http://hyperaud.io/ (related to people who are creating jsplayer)

The also opensourced their player:
https://github.com/hyperaudio/hyperaudio-lite

Sorry as I just saw your youtube talk which explains me a bit better why you kept everything simple and clientside! So I can understand its not a focus for this project.
